title: Siyi Zheng's Website
subtitle: Your awesome subtitle
description: >- # this means to ignore newlines until "baseurl:"
  A personal website of Siyi Zheng
author: Siyi Zheng
email: siyi.zheng206265@gmail.com
avatar: assets/images/hello.jpeg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/siyi-zheng-270787269/
github_url: https://github.com/Siyi-Zheng
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

timezone: Europe/London # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
permalink: /:categories/:year/:month/:day/:title:output_ext # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
