# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

remote_theme: chrisbobbe/jekyll-theme-prologue
title: My Website
description: "A short description of your project"

url: http://localhost:4000 # (optional) https://example.com, defaults to http://localhost:4000 in development

permalink: /:categories/:year/:month/:day/:title:output_ext # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

timezone: Europe/London # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Files to excludes from your website
# exclude:  
# - .gitignore
# - CNAME 
