title: Siyi Zheng's Website
author: Siyi Zheng
email: siyi.zheng206265@gmail.com
avatar: assets/images/hello.jpeg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/siyi-zheng-270787269/
github_url: https://github.com/Siyi-Zheng
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
